apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: scaffolder-backend-module-shell-exec
  description: |
    A custom Backstage scaffolder action to execute shell commands and scripts.
  links:
    - title: Repository
      url: https://github.com/Ruivalim/shell-exec
    - title: npm
      url: https://www.npmjs.com/package/@ruivalim/shell-exec
  annotations:
    github.com/project-slug: Ruivalim/shell-exec
  tags:
    - backstage
    - shell
    - exec
    - scaffold
    - action
    - plugin
    - template
spec:
  type: library
  owner: ruivalim
  lifecycle: production
